const fs = require('fs');
const path = require('path');
const jwt = require('jsonwebtoken');

const privateKey = fs.readFileSync(
  path.join(__dirname, '../private/rsa/jwt/private.key'),
  'utf-8',
);
const publicKey = fs.readFileSync(
  path.join(__dirname, '../private/rsa/jwt/public.key'),
  'utf-8',
);

/**
 * generate jwt-token for a user
 * A new token is generated by the RS256 algorithm and expires in 7 days
 * @param {String} username
 */
function generateJWTToken (username) {
  const payload = { user: username };
  const signOptions = { expiresIn: '7d', algorithm: 'RS256', issuer: username };
  return jwt.sign(payload, privateKey, signOptions);
}

/**
 * Verifies if the user owns the token
 * Returns true, if the toke is successfully verified.
 * Else return false
 * @param {String} username
 * @param {String} token
 */
function verifyJWTToken (username, token) {
  const verifyOptions = { exp: '7d', algorithm: ['RS256'], issuer: username };
  return jwt.verify(token, publicKey, verifyOptions, (err) => {
    if (err) {
      console.log(err);
      return false;
    }
    return true;
  });
}

module.exports = {
  generateJWTToken,
  verifyJWTToken,
};
